# Generated by Django 5.1.1 on 2025-06-28 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_userpresence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Thumbs Up'), ('👎', 'Thumbs Down'), ('❤️', 'Heart'), ('😂', 'Laughing'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry'), ('🎉', 'Party'), ('🔥', 'Fire'), ('💯', 'Hundred')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chatapp.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
